# intro to artifical neural networks
# can be used for classification and regression
# this script will be about REGRESSION

# the hyperbolic tangent activation function
# hyperbolic tangent = tanh(x)
# tanh(x) = (e^x - e^-x) / (e^x + e^-x)  --- e is eulers number
# the output ranges from -1 to 1 ALWAYS
tanh(1)
tanh(3)
# if the input to the tanh(x) is greater than 3, the output is 1
tanh(-3)
# if the input to tanh(x) is less than -3, the output is -1
# the most variability occurs when the input is between -3 and 3!!!!!!



# using the 9 AMES.RData file from asynch
str(ames)
tail(ames)
# we want to predict the fair selling price of a home in Ames, IA
# PRICE = price of the home divided by 1000000
# ROOMS = total number of rooms divided my 10
# BATHS = number of bathrooms divided by 10
# KITCHENS = number of kitchens divided by 10
# CARS = car capacity of garage divided by 10
# build an artifical neural network to predict the price of a property

# CURRENTLY IN R!!!!!!
# all neural network packages can ONLY TAKE IN NUMERIC DATA
# if we have categorical data, it must be converted to numeric

# all variables should have small values, should be between -3 and 3 at least!
# this is when using the HYPERBOLIC TANGENT FUNCTION!!

install.packages("neuralnet")
library(neuralnet)

# first arguement is the formula for prediction
# second is the dataframe it comes from
# hidden = how many hidden nodes in the network
# act.fct = the activation function to be used (either "tanh" or "logistic")
LOGCABIN <- neuralnet(PRICE ~ ., data = ames, hidden = 1, act.fct = "tanh")
plot(LOGCABIN)
# each time we build the model, we get different weights
# each time we build the model, random starting points are used and we converge to a local optimum
# must use set.seed() to keep it consistent
set.seed(1)
LOGCABIN <- neuralnet(PRICE ~ ., data = ames, hidden = 1, act.fct = "tanh")
plot(LOGCABIN)
# what does this plot actually tell us
# the first column is the input nodes
# the next column is the hidden node
# the third column is the output node
# the blue lines are bias terms (similar to the intercept in a linear model)
# the numbers are the weights for each input

# how does the neural network work????
# the new input values are multipled by the weights
# the bias term is also multiplied by its weight
# the summation of this value is then fed into the hidden node
# the hidden node then applies the activation function to this summation!!
# the output of the hidden node is multiplied by the weight of the hidden node
# the second bias term is multipled by its weight as well
# the summation of the hidden node output and the bias term output goes into the output node
# there is NO activation function in the output node!!
# so the final value found in the output node is the prediction!!

# predict the price of a new home
# variables MUST be in the SAME ORDER as the training data
NEST <- data.frame(ROOMS = 0.7, BATHS = 0.3, KITCHENS = 0.1, CARS = 0.2)
NEST
predict(LOGCABIN, NEST) * 1000000

DEN <- data.frame(ROOMS = 0.9, BATHS = 0.4, KITCHENS = 0.1, CARS = 0.2)
DEN
predict(LOGCABIN, DEN)


# using the logistic (sigmoid) function as the activation function
# logistic = (e^x) / (1 + e^x)  OR  1 / (1 + e^-x)  --- e is eulers number
# this is the same as the logistic function from logistic regression
# the output is always between 0 and 1
# when the input is greater than 6, the output is ~ 1
# when the input is less than -6, the output is ~ -1
# the most variabilty occurs between -6 and 6

# using the 9 HOLLYWOOD.RData from asynch
str(HOLLYWOOD)
tail(HOLLYWOOD)
# we want to predict how much revenue a movie will generate
# REVENUE = revenue generated by the movie (in billions)
# BUDGET = budget used to make the movie (in billions)
# RUNTIME = runtime of the movie (in hours)
# HORROR = if the movie is horror or thriller, then 1
# R.RATED = if its rated R, then 1

set.seed(1)
POPCORN <- neuralnet(REVENUE ~., data = HOLLYWOOD, hidden = 1, act.fct = "logistic")
plot(POPCORN)

# predict revenue for "The Grey"
WOLF <- data.frame(BUDGET = 0.025, RUNTIME = 1.95, HORROR = 0, R.RATED = 1)
WOLF
predict(POPCORN, WOLF) * 1000000000

MYERS <- data.frame(BUDGET = 0.015, RUNTIME = 1.75, HORROR = 1, R.RATED = 1)
MYERS
predict(POPCORN, MYERS) * 1000000000

# what is the signifcance of the activation function?
# without the activation function, the model simply becomes a linear regression problem
# with the activation function, we can model more complex events, such as non linear events


